version: 2.1

orbs:
  heroku: circleci/heroku@0.0.4

workflows:
  version: 2.1
  heroku_deploy:
    jobs:
      - build
      - deployDevelop:
          requires:
            - build
          filters:
            branches:
              only: develop
      - deployProduction:
          requires:
            - build
          filters:
            branches:
              only: master

jobs:
  build:
    docker:
      - image: circleci/node:10.15

    steps:
      - checkout
      
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deployDevelop:
    docker:
      - image: circleci/node:10.15

    executor: heroku/default

    steps:
      - heroku/install
      - checkout
      - setup_remote_docker
      
      - run:
          name: Build Docker image
          command: docker build --cache-from=app -t $HEROKU_APP_NAME_DEV .
      
      - run:
          name: Install Heroku CLI
          command: sudo curl https://cli-assets.heroku.com/install.sh | sh 
     
      - run:
          name: Login container
          command: heroku container:login

      - run:
          name: Relase the Heroku app
          command: heroku container:push web -a $HEROKU_APP_NAME_DEV

      - run:
          name: Relase the Heroku app
          command: heroku container:release web -a $HEROKU_APP_NAME_DEV

  deployProduction:
    docker:
      - image: circleci/node:10.15

    executor: heroku/default

    steps:
      - heroku/install
      - checkout
      - setup_remote_docker
      
      - run:
          name: Build Docker image
          command: docker build --cache-from=app -t $HEROKU_APP_NAME .
      
      - run:
          name: Install Heroku CLI
          command: sudo curl https://cli-assets.heroku.com/install.sh | sh 
     
      - run:
          name: Login container
          command: heroku container:login

      - run:
          name: Relase the Heroku app
          command: heroku container:push web -a $HEROKU_APP_NAME

      - run:
          name: Relase the Heroku app
          command: heroku container:release web -a $HEROKU_APP_NAME